name: translation_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cloud_firestore: ^5.6.6
  icons_plus: ^4.0.0
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
