// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyD7XplQNj4jZPJXFKz00M5U-SCnvFKvE',
    appId: '1:1058694520013:web:874af527b9e4e0c6d6dd84',
    messagingSenderId: '1058694520013',
    projectId: 'translation-app-8bc8e',
    authDomain: 'translation-app-8bc8e.firebaseapp.com',
    storageBucket: 'translation-app-8bc8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABr3ZHEacgG61YI4pGgU7UTg-ft-aN1R0',
    appId: '1:1058694520013:android:eee8ccb8946a289dd6dd84',
    messagingSenderId: '1058694520013',
    projectId: 'translation-app-8bc8e',
    storageBucket: 'translation-app-8bc8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPnipX4Rnevf6GIEqBSW2GrfRZlMm2aE',
    appId: '1:1058694520013:ios:b4735d8e180d767ed6dd84',
    messagingSenderId: '1058694520013',
    projectId: 'translation-app-8bc8e',
    storageBucket: 'translation-app-8bc8e.firebasestorage.app',
    iosBundleId: 'com.example.translationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARPnipX4Rnevf6GIEqBSW2GrfRZlMm2aE',
    appId: '1:1058694520013:ios:b4735d8e180d767ed6dd84',
    messagingSenderId: '1058694520013',
    projectId: 'translation-app-8bc8e',
    storageBucket: 'translation-app-8bc8e.firebasestorage.app',
    iosBundleId: 'com.example.translationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyD7XplQNj4jZPJXFKz00M5U-SCnvFKvE',
    appId: '1:1058694520013:web:b2bde67dda40cb25d6dd84',
    messagingSenderId: '1058694520013',
    projectId: 'translation-app-8bc8e',
    authDomain: 'translation-app-8bc8e.firebaseapp.com',
    storageBucket: 'translation-app-8bc8e.firebasestorage.app',
  );
}
